import { WEBINAR_WHATSAPP_URL } from "@/lib/webinar";
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] || char); }
export function confirmation(firstName: string) {
  const safeName = escapeHtml(firstName);
  return {
    subject: "Your spot is confirmed: Making AI Make Business Sense",
    text: `Hi ${firstName},\n\nYour spot is confirmed for Making AI Make Business Sense.\n\nSaturday, 10th October 2026\n6PM GMT+1 · Live online\n\nJoin the webinar WhatsApp group now for the joining link, reminders and event updates:\n${WEBINAR_WHATSAPP_URL}\n\nWe'll also email your joining details before the webinar. Bring one costly tool or slow task you would like to improve.\n\nSee you there,\nRun Rentless × Navrademy`,
    html: `<div style="margin:0 auto;max-width:580px;padding:38px 24px;font-family:Arial,sans-serif;color:#08211d;background:#f8f6ef"><p style="margin:0 0 28px;color:#e25930;font-size:12px;font-weight:bold;letter-spacing:2px">RUN RENTLESS × NAVRADEMY</p><h1 style="margin:0 0 22px;font-size:32px;line-height:1.1">Your spot is confirmed.</h1><p>Hi ${safeName},</p><p>You're registered for <strong>Making AI Make Business Sense</strong>.</p><p style="padding:20px 0;border-top:1px solid #bbc9c1;border-bottom:1px solid #bbc9c1"><strong>Saturday, 10th October 2026</strong><br>6PM GMT+1 · Live online</p><div style="margin:26px 0;padding:24px;background:#08211d;color:#fdfff4"><h2 style="margin:0 0 10px;font-size:23px;line-height:1.2">Join the event WhatsApp group.</h2><p style="margin:0 0 22px;line-height:1.5">Get the joining link, reminders and event updates in one place.</p><a href="${WEBINAR_WHATSAPP_URL}" style="display:inline-block;padding:15px 20px;background:#c6ff00;color:#08211d;font-size:16px;font-weight:bold;text-decoration:none">Join the WhatsApp group →</a></div><p>We'll also email your joining details before the webinar. Bring one costly tool or slow task you would like to improve.</p><p>See you there,<br><strong>Run Rentless × Navrademy</strong></p><p style="margin-top:30px;font-size:12px;color:#4e655c">Questions? Reply to this email or visit <a href="https://www.runrentless.com/contact" style="color:#08211d">runrentless.com/contact</a>.</p></div>`,
  };
}
